INSERT INTO Artist(artistName) VALUES
	("Lil Nas X"),
	("Justin Beiber"),
	("Polo G"),
	("Masked Wolf"),
	("Bruno Mars"),
	("Doja Cat"),
	("The Weeknd"),
	("Olivia Rodrigo"),
	("Los Legendarios"),
	("Giveon"),
	("Kali Uchis"),
	("Dua Lipa"),
	("Bad Bunny"),
	("Tiesto"),
	("Cardi B"),
	("Riton"),
	("Taylor Swift"),
	("Lil Tjay"),
	("The Kid Laroi"),
	("24kGoldn"),
	("Myke Towers"),
	("Duncan Laurence"),
	("Harry Styles"),
	("Glass Animals"),
	("ATB"),
	("Sech");
	
INSERT INTO Songs(artistID,songName) VALUES
	(1,"Montero"),
	(2,"Peaches"),
	(3,"Rapstar"),
	(4,"Astronaut In The Ocean"),
	(5,"Leave The Door Open"),
	(6,"Kiss Me More"),
	(7,"Save Your Tears"),
	(8,"Drivers License"),
	(9,"Fiel"),
	(10,"Hearbreak Anniversary"),
	(11,"Telepatia"),
	(8,"Deja Vu"),
	(12,"Levitating"),
	(7,"Blinding Lights"),
	(2,"Hold On"),
	(13,"Dakiti"),
	(14,"The Business"),
	(15,"Up"),
	(16,"Friday"),
	(17,"Mr Perfectly Fine"),
	(18,"Calling My Phone"),
	(19,"Without You"),
	(20,"Mood"),
	(21,"Badido"),
	(6,"Streets"),
	(22,"Arcade"),
	(23,"Watermelon Sugar"),
	(24,"Heat Waves"),
	(25,"Your Love"),
	(26,"911");
	
INSERT INTO Contributor(contributorName, contribution) VALUES
	("David Biral","Writer"),
	("Omer Fedi","Producer"),
	("Andrew Wotman","Writer"),
	("HARV","Producer"),
	("Alexander Wu","Writer"),
	("Einer Bankz","Producer"),
	("Harry Michael","Writer"),
	("Tyron Hapi","Producer"),
	("Daniel Nigro","Guitar"),
	("Christian Linares","Drums"),
	("KOZ","Singer"),
	("DaBaby","Singer"),
	("Tainy","Guitar"),
	("La Paciencia","Drums"),
	("DJ SwanQo","Producer"),
	("Yung Dza","Writer"),
	("James D Steed","Drums"),
	("Jordan Thorpe","Guitar");
	
INSERT INTO ContributeTo(contributorID,songID) VALUES	
	(1,1),
	(2,1),
	(3,2),
	(4,3),
	(5,4),
	(6,5),
	(7,6),
	(8,7),
	(9,8),
	(10,9),
	(11,10),
	(12,11),
	(13,12),
	(14,12),
	(5,13),
	(4,14),
	(6,15),
	(16,16),
	(17,16),
	(18,16),
	(15,17),
	(8,18),
	(9,19),
	(12,20),
	(3,21),
	(2,22),
	(11,22),
	(17,23),
	(4,24),
	(9,27),
	(10,27),
	(11,28),
	(14,29),
	(1,30);
	
INSERT INTO KaraokeFile(songID,songVersion) VALUES	
	(1,"Solo"),
	(1,"Duet"),
	(2,"Solo"),
	(3,"Solo"),
	(4,"Solo"),
	(4,"Duet"),
	(5,"Solo"),
	(5,"Duet"),
	(6,"Solo"),
	(7,"Solo"),
	(7,"Duet"),
	(8,"Solo"),
	(8,"Duet"),
	(9,"Solo"),
	(10,"Solo"),
	(11,"Solo"),
	(12,"Solo"),
	(13,"Solo"),
	(14,"Solo"),
	(14,"Duet"),
	(15,"Solo"),
	(15,"Duet"),
	(16,"Solo"),
	(17,"Duet"),
	(18,"Solo"),
	(19,"Solo"),
	(20,"Solo"),
	(20,"Duet"),
	(21,"Duet"),
	(22,"Solo"),
	(22,"Duet"),
	(23,"Solo"),
	(24,"Solo"),
	(25,"Solo"),
	(25,"Duet"),
	(26,"Duet"),
	(27,"Solo"),
	(28,"Solo"),
	(29,"Solo"),
	(30,"Duet");